export FLASK_APP=main.py$FLASK_APP
export POSTGRES_URI="localhost:5432"$POSTGRES_URI
export POSTGRES_DB="test"$POSTGRES_DB
export POSTGRES_USERNAME="jorgelara"$POSTGRES_USERNAME
export POSTGRES_PASSWORD="example"$POSTGRES_PASSWORD